### ISSUE TITLE
请教下Cocos Creator引用axios

### ISSUE THREAD

**Issue by JakeWoki** [shrinktofit/can-i-use-npm-in-cocos-creator#1]
```
用法：CommonJS 模块
import axios from "axios/dist/axios.min.js";
模块“axios/dist/axios.min.js”可能没有相应的类型声明。
为了获取类型提示，将以下内容拷贝至任何 `.d.ts` 文件中，并在 tsconfig.json 中引用该 `.d.ts` 文件。
declare module "axios/dist/axios.min.js" {
                    export * as default from 'axios';
                }
```
在 tsconfig.json 中引用该 `.d.ts` 文件，这个是怎么引用的？
还有这样引入后怎么使用？

**Comment by shrinktofit** [comment]
引用后直接使用就行了啊，可以这样试试：

```ts
/// <reference types="当前文件到目标 .d.ts 文件的相对路径"/>

// 上面这个指令⬆️ 引用 .d.ts，参见：https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-

import axio from 'axios/dist/axios.min.js';

axio.xxxxx
```

**Comment by JakeWoki** [comment]
Cocos Creator v3.5.2，axios v0.27.2
引入`import axios from 'axios/dist/axios.min.js'`
报错：
```Javascript
TypeError: __checkObsolete__ is not a function
    at Object.execute (c50adb79804ee01cfa4cf09c86b93d61ed6f4861.js:38:7)
    at doExec (system.js:444:34)
    at postOrderExec (system.js:440:12)
    at system.js:430:30
    at Array.forEach (<anonymous>)
    at postOrderExec (system.js:428:12)
    at system.js:430:30
    at Array.forEach (<anonymous>)
    at postOrderExec (system.js:428:12)
    at system.js:406:14
```

引入`import axios from 'axios'`
报错：
```Javascript
Error: Unable to resolve bare specifier '__unresolved_5' from http://localhost:7456/scripting/x/chunks/c6/c6f1969f036e8d9d4d332fe596d233446b94550f.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
index.js:1 PromiseRejectionEvent {isTrusted: true, reason: Error: Unable to resolve bare specifier '__unresolved_7' from http://localhost:7456/scripting/x/chu…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
(anonymous) @ index.js:1
system.js:679 Uncaught (in promise) Error: Unable to resolve bare specifier '__unresolved_7' from http://localhost:7456/scripting/x/chunks/f4/f4bf496bbf55ef75f3092a3c0526b73aefbf9906.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
index.js:1 PromiseRejectionEvent {isTrusted: true, reason: Error: Unable to resolve bare specifier '__unresolved_4' from http://localhost:7456/scripting/x/chu…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
(anonymous) @ index.js:1
system.js:679 Uncaught (in promise) Error: Unable to resolve bare specifier '__unresolved_4' from http://localhost:7456/scripting/x/chunks/89/8978bd75d76636d037222c9d8c343ba48da3dc0c.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
index.js:1 PromiseRejectionEvent {isTrusted: true, reason: Error: Unable to resolve bare specifier '__unresolved_1' from http://localhost:7456/scripting/x/chu…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
(anonymous) @ index.js:1
system.js:679 Uncaught (in promise) Error: Unable to resolve bare specifier '__unresolved_1' from http://localhost:7456/scripting/x/chunks/45/45c1923a5a64a5d6f4f2f0bed16b52f5d8b74828.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
index.js:1 PromiseRejectionEvent {isTrusted: true, reason: Error: Unable to resolve bare specifier '__unresolved_4' from http://localhost:7456/scripting/x/chu…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
(anonymous) @ index.js:1
system.js:679 Uncaught (in promise) Error: Unable to resolve bare specifier '__unresolved_4' from http://localhost:7456/scripting/x/chunks/e8/e8bccfa5c86dcf16a6c21f8091ce6030eda98a2a.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
index.js:1 PromiseRejectionEvent {isTrusted: true, reason: Error: Unable to resolve bare specifier '__unresolved_2' from http://localhost:7456/scripting/x/chu…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
(anonymous) @ index.js:1
system.js:679 Uncaught (in promise) Error: Unable to resolve bare specifier '__unresolved_2' from http://localhost:7456/scripting/x/chunks/9d/9da12e344b07966501de2f4a313bb5c8cba3672f.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
index.js:1 PromiseRejectionEvent {isTrusted: true, reason: Error: Unable to resolve bare specifier '__unresolved_2' from http://localhost:7456/scripting/x/chu…, type: 'unhandledrejection', target: Window, currentTarget: Window, …}
(anonymous) @ index.js:1
system.js:679 Uncaught (in promise) Error: Unable to resolve bare specifier '__unresolved_2' from http://localhost:7456/scripting/x/chunks/b3/b3813b8c5a732c4a6269dd556d7b1ffc4cafa6be.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:679:11)
    at SystemJS.systemJSPrototype.resolve (system.js:675:99)
    at SystemJS.systemJSPrototype.resolve (system.js:1020:24)
    at SystemJS.systemJSPrototype.resolve (system.js:1208:26)
    at system.js:336:39
    at Array.map (<anonymous>)
    at system.js:334:43
```
用不了

**Comment by JakeWoki** [comment]
把library、local、profiles等文件夹删了，重新运行可以了
